from enum import StrEnum

ASDEX_STYLES = ["runway", "taxiway", "apron", "structure"]
BCG_MIN = 1
BCG_MAX = 40
FILTER_MIN = 0
FILTER_MAX = 40
LINE_STYLE_NONE = "none"
LINE_STYLE_SOLID = "solid"
LINE_STYLE_LONG_DASHED = "longDashed"
LINE_STYLE_SHORT_DASHED = "shortDashed"
LINE_STYLE_LONG_SHORT_DASHED = "longDashShortDash"
LINE_STYLES = [
    LINE_STYLE_NONE,
    LINE_STYLE_SOLID,
    LINE_STYLE_LONG_DASHED,
    LINE_STYLE_SHORT_DASHED,
    LINE_STYLE_LONG_SHORT_DASHED,
]
LINE_THICKNESS_MIN = 1
LINE_THICKNESS_MAX = 3
PROPERTY_TYPE_LINE = "line"
PROPERTY_TYPE_POINT = "point"
PROPERTY_TYPE_POLYGON = "polygon"
PROPERTY_TYPE_SYMBOL = "symbol"
PROPERTY_TYPES = [
    PROPERTY_TYPE_LINE,
    PROPERTY_TYPE_POINT,
    PROPERTY_TYPE_POLYGON,
    PROPERTY_TYPE_SYMBOL,
]
SYMBOL_STYLE_OBSTRUCTION1 = "obstruction1"
SYMBOL_STYLE_OBSTRUCTION2 = "obstruction2"
SYMBOL_STYLE_HELIPORT = "heliport"
SYMBOL_STYLE_NUCLEAR = "nuclear"
SYMBOL_STYLE_EMERGENCY_AIRPORT = "emergencyAirport"
SYMBOL_STYLE_RADAR = "radar"
SYMBOL_STYLE_IAF = "iaf"
SYMBOL_STYLE_RNAV_ONLY = "rnavOnlyWaypoint"
SYMBOL_STYLE_RNAV = "rnav"
SYMBOL_STYLE_AIRWAY_INTERSECTION = "airwayIntersections"
SYMBOL_STYLE_NDB = "ndb"
SYMBOL_STYLE_VOR = "vor"
SYMBOL_STYLE_OTHER_WAYPOINTS = "otherWaypoints"
SYMBOL_STYLE_AIRPORT = "airport"
SYMBOL_STYLE_SATELLITE_AIRPORT = "satelliteAirport"
SYMBOL_STYLE_TACAN = "tacan"
SYMBOL_STYLE_DME = "dme"
SYMBOL_STYLES = [
    SYMBOL_STYLE_OBSTRUCTION1,
    SYMBOL_STYLE_OBSTRUCTION2,
    SYMBOL_STYLE_HELIPORT,
    SYMBOL_STYLE_NUCLEAR,
    SYMBOL_STYLE_EMERGENCY_AIRPORT,
    SYMBOL_STYLE_RADAR,
    SYMBOL_STYLE_IAF,
    SYMBOL_STYLE_RNAV_ONLY,
    SYMBOL_STYLE_RNAV,
    SYMBOL_STYLE_AIRWAY_INTERSECTION,
    SYMBOL_STYLE_NDB,
    SYMBOL_STYLE_VOR,
    SYMBOL_STYLE_OTHER_WAYPOINTS,
    SYMBOL_STYLE_AIRPORT,
    SYMBOL_STYLE_SATELLITE_AIRPORT,
    SYMBOL_STYLE_TACAN,
    SYMBOL_STYLE_DME,
]
SYMBOL_SIZE_MIN = 1
SYMBOL_SIZE_MAX = 4
TEXT_SIZE_MIN = 0
TEXT_SIZE_MAX = 5


class SymbolStyle(StrEnum):
    OBSTRUCTION1 = SYMBOL_STYLE_OBSTRUCTION1
    OBSTRUCTION2 = SYMBOL_STYLE_OBSTRUCTION2
    HELIPORT = SYMBOL_STYLE_HELIPORT
    NUCLEAR = SYMBOL_STYLE_NUCLEAR
    EMERGENCY_AIRPORT = SYMBOL_STYLE_EMERGENCY_AIRPORT
    RADAR = SYMBOL_STYLE_RADAR
    IAF = SYMBOL_STYLE_IAF
    RNAV_ONLY = SYMBOL_STYLE_RNAV_ONLY
    RNAV = SYMBOL_STYLE_RNAV
    AIRWAY_INTERSECTION = SYMBOL_STYLE_AIRWAY_INTERSECTION
    NDB = SYMBOL_STYLE_NDB
    VOR = SYMBOL_STYLE_VOR
    OTHER_WAYPOINTS = SYMBOL_STYLE_OTHER_WAYPOINTS
    AIRPORT = SYMBOL_STYLE_AIRPORT
    SATELLITE_AIRPORT = SYMBOL_STYLE_SATELLITE_AIRPORT
    TACAN = SYMBOL_STYLE_TACAN
    DME = SYMBOL_STYLE_DME

    def from_type(table: str, type: str) -> "SymbolStyle":
        if table == "VHF":
            if type[0:2] == "V ":
                return SymbolStyle.VOR
            if type[0:2] == " D":
                return SymbolStyle.DME
            if type[1:2] == "D" or type[1:2] == "T":
                return SymbolStyle.TACAN
        if table == "NDB":
            if type[0:1] == "H":
                return SymbolStyle.NDB
        else:
            if type[1:2] == "I":
                return SymbolStyle.IAF
            if type[0:1] == "C":
                return SymbolStyle.AIRWAY_INTERSECTION
            if type[0:1] == "W":
                return SymbolStyle.RNAV_ONLY
            return SymbolStyle.OTHER_WAYPOINTS
        return None
