class RunwayRecord:
    def __init__(self, db_record: dict):
        self.area = db_record.get("area")
        self.airport_id = db_record.get("airport_id")
        self.region = db_record.get("region")
        self.runway_id = db_record.get("runway_id")
        self.length = db_record.get("length")
        self.bearing = db_record.get("bearing")
        self.lat = db_record.get("lat")
        self.lon = db_record.get("lon")
        self.gradient = db_record.get("gradient")
        self.ellipsoidal_height = db_record.get("ellipsoidal_height")
        self.threshold_elevation = db_record.get("threshold_elevation")
        self.displaced_threshold = db_record.get("displaced_threshold")
        self.tch = db_record.get("tch")
        self.width = db_record.get("width")
        self.tch_id = db_record.get("tch_id")
        self.ls_ident = db_record.get("ls_ident")
        self.cat = db_record.get("cat")
        self.stopway = db_record.get("stopway")
        self.ls_ident_2 = db_record.get("ls_ident_2")
        self.cat_2 = db_record.get("cat_2")
        self.description = db_record.get("description")
        self.record_number = db_record.get("record_number")
        self.cycle_data = db_record.get("cycle_data")
